# This is a workflow that gets triggered when we merge release/feature branches into Master and Auto PR into all the Release/Feature Branches
on:
  push:
    branches:
      - 'main' # Only Master 
jobs:
 metadata: #  A matrix allows you to create multiple jobs by performing variable substitution in a single job definition. A job matrix can generate a maximum of 256 jobs per workflow run
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }} #key-value pair containg feature,release branches 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate matrix
        id: generate-matrix  
        # 1.List all the directories (optional)
        # 2.Fetch all the git branches before we carry out branch operations or subsequent git operation would fail
        # 3.Strip origin/remote as the GitHub action to generate auto pr automatically appends origin/remote
        # 4.Generate matrix in the json format containing all the matched branches
        run: |
          ls -ltr;
          git fetch --all 
          RELEASE_BRANCHES=`git branch -a --list '*RC*'`;     
          FEATURE_BRANCHES=`git branch -a --list '*feature/*'`;
          
          for index in ${!RELEASE_BRANCHES[@]}; 
          do  # Also, quote indices
           RELEASE_FEATURE_BRANCHES=( "${RELEASE_BRANCHES[$index]}" "${FEATURE_BRANCHES[$index]}" )
          done
          
           ## echo 'After combining Release and Feature Branches --- ' ${RELEASE_FEATURE_BRANCHES[@]}         
           ## for branch in ${RELEASE_FEATURE_BRANCHES[@]}; 
           ## do
           ##  echo 'Current Development Release branches are - ' $branch
           ## done    
           
          MATRIX_RELEASE_BRANCHES_JSON="["
          for BRANCHES in ${RELEASE_FEATURE_BRANCHES[@]} 
          do
             release_branch=${BRANCHES};
             ## echo "Release branch is in for loop" $release_branch
             branch_variable=$(sed -e 's#^remotes/origin/##' <<< "${BRANCHES}" )
             echo "After stripping remotes/origin current for in " ${branch_variable}
             MATRIX_RELEASE_BRANCHES_JSON+=$(sed 's/^/"/;s/$/"/' <<< "${branch_variable}")
          done
          MATRIX_RELEASE_BRANCHES_JSON="${MATRIX_RELEASE_BRANCHES_JSON//\"\"/\", \"}"
          MATRIX_RELEASE_BRANCHES_JSON+="]"
          MATRIX_JSON="{\"branches\": ${MATRIX_RELEASE_BRANCHES_JSON}}"
          echo "${MATRIX_JSON}"
          echo "::set-output name=matrix::${MATRIX_JSON}"
 ## Generate Auto PR to the all the branches listed in the matrix.         
 pullRequestToReleaseBranches:
    needs: metadata
    runs-on: ubuntu-latest
    strategy:
     matrix: ${{ fromJson(needs.metadata.outputs.matrix) }}
    steps:               
     - uses: actions/checkout@v2
       with:
          ref: '${{ matrix.branches }}'    
      
     - name: Create report file
       run: date +%s > report.txt
     ## Reset the promotion branch before we create a pull request to abandon any changes to the master branch if any .   
     - name: Reset promotion branch
       run: |
            git fetch origin master:master
            git reset --hard master
     - name: Set output variables
       id: vars
       run: |
              echo "::set-output name=pr_title::Pr into Release/Feature Branch ${{ matrix.branches }} from Master after the release $(date +%d-%m-%Y)"
              echo "::set-output name=pr_body::This PR was auto-generated on $(date +%d-%m-%Y) \
                by [create-pull-request](https://github.com/AAInternal/AMPS-API)."     
              echo "::set-output name=pr_commit_message::GitHub <noreply@github.com>"
     ## Create an Auto PR using the GitHub action from peter-evans         
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v3
       with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message:  ${{ steps.vars.outputs.pr_commit_message }}
            committer: GitHub <noreply@github.com> 
            author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            body: ${{ steps.vars.outputs.pr_body }}
            title: ${{ steps.vars.outputs.pr_title }}
            labels: automated pr
            reviewers: Preetish.Madalia@aa.com,Naseer.Mohammed.abdul@aa.com,Sudeep.kumar.varma.Ganapathiraju@aa.com
            team-reviewers : DL_TechOps_Knights@aa.com
            branch: 'master_promotion_${{ matrix.branches }}'
          
    
